using System.Text.Json.Serialization;

namespace Chorectl.Core.Domain.Dependabot;

/// <summary>
/// A single open Dependabot pull request, with its GitHub state and classification.
/// </summary>
public sealed record DependabotPr
{
    /// <summary>Name of the repo the PR belongs to (personal-account scope, so no owner prefix).</summary>
    public required string Repo { get; init; }

    /// <summary>Pull request number.</summary>
    public required int Number { get; init; }

    /// <summary>Pull request title, as generated by Dependabot.</summary>
    public required string Title { get; init; }

    /// <summary>Web URL of the pull request.</summary>
    public required string Url { get; init; }

    /// <summary>Name of the PR's head branch.</summary>
    public required string HeadRefName { get; init; }

    /// <summary>Name of the dependency being updated, parsed from the title.</summary>
    public string? DependencyName { get; init; }

    /// <summary>Version the dependency is being updated from, parsed from the title.</summary>
    public string? FromVersion { get; init; }

    /// <summary>Version the dependency is being updated to, parsed from the title.</summary>
    public string? ToVersion { get; init; }

    /// <summary>Semver bump level of this update.</summary>
    public SemverLevel SemverLevel { get; init; }

    /// <summary>Whether this PR groups multiple dependency updates together.</summary>
    public bool IsGrouped { get; init; }

    /// <summary>Whether this PR addresses a security advisory.</summary>
    public bool IsSecurityUpdate { get; init; }

    /// <summary>Aggregate CI status.</summary>
    public CiStatus Ci { get; init; }

    /// <summary>Review status.</summary>
    public ReviewStatus Review { get; init; }

    /// <summary>Raw <c>mergeStateStatus</c> from the GitHub API (CLEAN, DIRTY, BLOCKED, BEHIND, UNSTABLE, UNKNOWN).</summary>
    public required string MergeStateStatus { get; init; }

    /// <summary>
    /// PR body, only populated by <c>RefetchAsync</c> - checked for Dependabot's temporary
    /// rebase-in-progress banner (see <see cref="Classifier.HasRebaseBanner"/>). Excluded from
    /// <c>--json</c> output: it's Dependabot's full raw changelog HTML, not user-facing state.
    /// </summary>
    [JsonIgnore]
    public string? Body { get; init; }

    /// <summary>Whether the PR is a draft.</summary>
    public bool IsDraft { get; init; }

    /// <summary>When the PR was last updated.</summary>
    public DateTimeOffset UpdatedAt { get; init; }
}
